# Generated by Django 3.1.4 on 2021-02-07 20:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import storages.backends.ftp


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file',
                 models.FileField(storage=storages.backends.ftp.FTPStorage(),
                                  upload_to='ontologies/',
                                  validators=[
                     django.core.validators.FileExtensionValidator(
                         ['owl'])],
                     verbose_name='Arquivo')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ontology',
                'verbose_name_plural': 'Ontologies',
            },
        ),
    ]
