# Generated by Django 3.1.4 on 2021-03-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
    ]
