# Generated by Django 3.1.4 on 2021-03-08 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ontology_app', '0002_jogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jogo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
