# Generated by Django 3.1.4 on 2021-03-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology_app', '0004_jogo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
